### PR TITLE
Support for Model D Wireless

### PR DESCRIPTION
**Pull request by dxbednarczyk**
From my testing, all that needed to change was the USB ID checking. Both the Model O Wireless and Model D Wireless use (mostly) the same guts, so settings map cleanly.

### CODE REVIEW

**Comment by dbednar230** [comment]
I guess this PR kind of gets rid of the naming scheme... might want to review that

**Comment by korkje** [comment]
This is great, thanks for the PR! I'll just pull this into a separate branch first I think, so I can update the readme with information and credits. And I guess I should update the name of the repo and executable as well, as `mow` doesn't really make sense when there is support for more mice.

**Comment by dbednar230** [comment]
I feel as if it might be beneficial to split up the backend and frontend (meaning HIDAPI and CLI tooling) into different packages, would help if anyone wanted to make a GUI, TUI, or some automated tool, they could just import this git repo. That's a story for another PR, I've already started to kind of recreate this in Go [here](https://github.com/dbednar230/gwm-tui) using that model.

**Comment by dxbednarczyk** [comment]
Closing as my master branch has different changes, irrelevant to this PR

**Pull request closed without merging**
